export const TIMELINE_INNER_WIDTH_PX = 10000;
export const TIMELINE_BORDER_WIDTH_PX = 1;
export const TIMELINE_X_PADDING_PX = 12;
export const MAX_HOURS = 1000;
export const WIDTH_BETWEEN_MARKS_PX =
  (TIMELINE_INNER_WIDTH_PX - TIMELINE_X_PADDING_PX * 2) / MAX_HOURS;
