version: "3.8"

services:
  1000_hour_journeys_frontend:
    container_name: 1000_hour_journeys_frontend
    image: 1000_hour_journeys_frontend
    build: 
      target: production
    envirnoment:
      - REACT_APP_API_BASE=${REACT_APP_API_BASE}
    ports:
      - 80:80