version: "3.8"

services:
  1000_hour_journeys_frontend:
    container_name: 1000_hour_journeys_frontend
    image: 1000_hour_journeys_frontend
    build: 
      target: production
    ports:
      - 80:80