name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Build and run latest code
        id: docker_build
        env:
          REACT_APP_API_BASE: ${{ secrets.REACT_APP_API_BASE }}
        run: ./docker_start.sh